### ISSUE TITLE
Construction Design

### ISSUE THREAD

**Issue by supernative** [supernative/random#1]
A practical guide to creating effective construction designs and systems with quick turnaround times.

**Comment by supernative** [comment]
**Construction Process**

It requires a task with input-output states of their respective substrates and the construction process will include developing all necessary intermediates for achieving the desired outcome.

We only are interested in the construction process in terms of whether the desired mapping from input to output will be possible or not. For all those possible solutions, there would be a constructor which will carry out the transformation process through the _construction_ process, however we can abstract it out as an unphysical entity that can be found in nature given the constraints.

Ultimately we are looking for statements about some pair of constraints given that as states of the attributes of their substrates and whether a construction process can link the two via a physical process that determines one of two possible outcomes:
- [ ] The construction process is possible with accuracy of _%_,
- [ ] The construction process is not possible because of _*_.

The symbol _*_ indicates the relevant property that prohibits certain transformation to be performed on the holding subsystem and _%_ indicates the percent accuracy given an epsilon.

The constructors are possible if not known to be violating some laws of physics and impossible under certain circumstances. If those laws are not understood enough, the statement would include the counter factual information regarding the attempt.

If some task is possible, it cannot be made to become impossible ever again and some task that is impossible, it shall provide us with the knowledge of what goes wrong.

**Key Aspects**

- [ ] Task
- [ ] Construction
- [ ] Knowledge
- [ ] Measurement
- [ ] Regular Network
- [ ] Composition Principle
- [ ] Computation
- [ ] Resource Acquisition
- [ ] Optimism
- [ ] Counterfactual
- [ ] Abstract Constructor
- [ ] Programmable Constructor

Constructors are one valid if it can retain its ability to perform the same functions again and again.

Tests are necessary part of the application where we would want to know what possible constructions are available regardless of the resource considerations.

For those states that aren't fully constructor theoretic could be approximated to subsystems that would be compatible.

**Comment by supernative** [comment]
**Task : Key Aspects**

Task is formatted as follows:

`input attribute of substrate -> output attribute of substrate`

The *arrow* indicates the construction step where a constructor would transform the substrates.

When defining a task, the state attributes of the substrate may not be readily available at the time of assignment. For those cases, the abstract constructors can be approximated and linked together at latent points of reference.

**Preparation of Substrate**

A valid task is one that has all of its associated pairs in their legitimate use and the mapping between two different legitimate attributes to be valid.

A substrate may have any kind of attribute, so long as they could go through changes via some physical process. A process that prepares a substrate to be measurable by some other means at one of the two possible levels of description is said to occur together in a construction process where one goes through change via some transformation on another, while its subsystem comes in with measurement that the other prepares itself to be established.

There are two types of tasks:
- [ ] Parallel
- [ ] Serial

They could be grouped into a network of composite task unit, where the outputs of one links its outputs to the inputs of the other from top to bottom.

**Parallel** composition of task _A • B_ is the task _T = X + Y_ where _for all (x and y) in (X and Y)_, _T_ happens independent at _A_ and _B_ where their cartesian product of computation variable commute with the computation variable of the other and added together.

**Serial** composition of the task _AB_ would be so that the effect of _B_ would go directly into the input of _A_ once performs _B_ first on a substrate.

**Key Aspects**

- [ ] Locality Principle
- [ ] Regular Network
- [ ] Composition of Task Heads

**Comment by supernative** [comment]
**Programmable Constructor**

These are software programs developed for initializing a system with naturally occurring resource that provides generic access to some channel of information about their environment.

The program will first approximate those constructors and use them to build some reversible information processing substrates.

The substrates will be used to define computation medium and other construction tasks that will be required to attain a stable baseline for releasing the dependencies from original instance of the constructor.

A standard template for writing the programs follow the standards below:

- [ ] Define computation as permutation of states of some set of two or more variables
- [ ] Each permutation of state maps the state observable to its ordering and all observables are composed together via union of their respective states.
- [ ] Define a criteria for type casting some system to be of reversible kind where the media defines reversible information processing model
- [ ] Using criteria, any pair of subsystems could parallelize their state permutation order where one becomes aware of the other and their union forms the computation basis for constructing a reversible information processing media
- [ ] Allow commutation of information variable whenever two or more subsystems share a common computation variable whose function define the computation medium
- [ ] Measure performance of the programmable constructor based on how well it retains the functional capability over infinity

**Counterfactual Statement**

- [ ] What is so significant about that?
- [ ] How is that way of describing physical processes better than laws of motion and initial-final form?
- [ ] In what way the dichotomy that constructor theoretic statements can apply be used for better understanding the laws of physics?

Clocks can count indefinitely in a computer without actually computing anything other than the integer valued function at that point.

Suppose two states are defined: _left_ and _right_.

A program is written that can put either state to hold some definite quantity and measure what quantity any state has given the states.

If the binary variable define one state with the other being the opposite, then measuring only one state could tell us what the other state has.

Consider a situation where the system crashes while executing the first part of the sequence. Now we don't know what that state had, so no idea what the other could have neither from measuring the first one nor measuring it directly as the program will have assigned some order following a sequential process.

If one of the state could hold counterfactual information about the other and due to that information being present the other is said to have been bounded outside, then no measure on the second could tell us anything more than what we already knew. Also the crashing event now cannot assert any effect on the other one. This is a law of physics which not only says what happens and doesn't but mainly could explain why something could happen or could not happen by any means when certain information is present.

In fact we don't have place the other one for measurement at all since we can assert all the logical conclusions from everything else that refers to it while it says something about what can and cannot be measured, regardless of what attributes are being tested.

**Comment by supernative** [comment]
**Programmable Constructor**

It is going to be one of _busy beaver_ type games. The game will be played by two kinds of entities, both of which are physical objects.

The two physical objects will be jointly isolated and represent a system with its possible subsystem states.

_agent_ : contains a set of states defined for the substrate
_constructor_ : causes transformation on states to produce another state.

| Input    | Output       |                |                |
|----------|--------------|----------------|----------------|
|          |              | Abstract       | Physical       |
| Abstract | Abstract     | Computation    | Preparation    |
| Physical | Physical     | Measurement    | Other construction |
|          |              |                |                |

**Table 1: A classification of constructions**
